### ISSUE TITLE
Do you have any publications for reference?

### ISSUE THREAD

**Issue by Tunaaaaa** [zhouzhenghong-gt/self-supervised-3D-DSA-reconstructio-network#1]
Hello! Im very interested about your open codes and methods. Do you have any published articles to learn from?
Thank you very much~

**Comment by zhouzhenghong-gt** [comment]
Hi@Tunaaaaa,
Our paper is under review, thanks for your interest!

**Comment by Tunaaaaa** [comment]
good to know that. looking forward to your article~
