### ISSUE TITLE
nerf

### ISSUE THREAD

**Issue by ttkxyy** [zhouzhenghong-gt/self-supervised-3D-DSA-reconstructio-network#3]
Hello, could you please tell me if you have run through and achieved the effect in the author's paper for naf_cbct this project?Thank you.

**Comment by zhouzhenghong-gt** [comment]
Hi, this work was completed before NAF, so I haven't tried NAF_CBCT for comparison. Additionally, it's worth noting that the tasks differ between the two approaches: this repository is CNN-based and trains and tests on different patients, while NAF is a NeRF-based method that trains and tests on a single patient.
