### ISSUE TITLE
Regarding the inconsistency between code and paper

### ISSUE THREAD

**Issue by windrise** [zhouzhenghong-gt/self-supervised-3D-DSA-reconstructio-network#4]
您好，您在代码的load_data.py中使用的image_array_proj是一个多个views的图片的叠加, 然后我看到在train.py中seg对应image_array_proj， 同时您在计算网络的loss时，是用3d-Unet网络的输出和seg进行计算的。按照论文的描述计算loss的标注应该是3d体素吧？ 这里我没想明白我哪里想错了，麻烦您能给我解答一下疑惑！！！ 非常感谢

**Comment by zhouzhenghong-gt** [comment]
您好，seg此处是对load_data文件中的image_array_pro，大小是(views, h, w)，表示输入2D图像。loss的计算是计算 3d-Unet网络的输出的投影 与 输入2D图像 之间的MSE loss，我们没有使用3D标注。请您参考loss文件夹下面的mse_loss.py文件。

**Comment by windrise** [comment]
感谢您的回复，这点我可以理解的，如果网络的输出是多个views的2d图像，那在make_train_predict0.py脚本中，第100行左右加载并转换的image_array这个变量是3为的体素还是多个views的2d图像呢？其实，我的主要疑惑是：网络的输出结果（stage2）多views的2d图像是如何经过后处理生成3d体素的？  （因为没有相关数据，我自己的数据的结果比较奇怪，应该是我的理解有问题，抱歉哈，麻烦您啦！）。

**Comment by zhouzhenghong-gt** [comment]
image_array这个是三维的体素，是上一阶段的输出结果。

您提到了“网络的输出是多个views的2d图像”，其实3d U-Net网络的输出是三维的体素，但是我们会通过投影的方式得到二维图像从而监督3d U-Net网络。投影二维是为了计算损失，而不是作为最后的输出结果。

正如我在repo中所提到的，目前释放出的模型/代码是在模拟数据上进行训练的版本，我不清楚这可不可能是导致您数据结果奇怪的原因。

希望这样说明可以帮助您更好的理解。

**Comment by windrise** [comment]
非常感谢您的答复！

我也是使用的模拟drr数据。也就是投影二维这部分的代码目前还没有发布对吧？ 因为我看到代码中似乎没有从3d到2d投影部分，而在您的论文中是这么描述的。 

非常感谢哈

**Comment by zhouzhenghong-gt** [comment]
我们发布了投影相关的一部分代码，在https://github.com/zhouzhenghong-gt/self-supervised-3D-DSA-reconstructio-network/blob/main/loss/mse_loss.py#L25C10-L25C10 中的oblique_project1函数。对应论文"Problem description and response strategy"中的(Equation 3)。

此外，由于这部分代码是两年前的，可能现在存在一些问题。

**Comment by windrise** [comment]
非常感谢您的回复，感觉你们的这种做法挺有意思的，我回去研究一下。
